-- 코드를 작성해주세요
SELECT E.ID, 
    CASE WHEN CHILD_CNT IS NULL THEN 0 ELSE CHILD_CNT END AS CHILD_COUNT
FROM ECOLI_DATA E 
LEFT JOIN 
    (SELECT A.ID, COUNT(*) AS CHILD_CNT
        FROM ECOLI_DATA A, ECOLI_DATA B
        WHERE A.ID = B.PARENT_ID
     GROUP BY A.ID
    ) C
 ON E.ID = C.ID
ORDER BY 1