-- 코드를 작성해주세요
-- CONV : 숫자 기반 시스템을 다른 진법의 수로 표시해줍니다
-- CONV(데이터, 원본 진법, 변환할 진법) 
-- 비트연산자 : 부모와 자식의 형질이 같아야 함 
SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CHILD, ECOLI_DATA PARENT
WHERE CHILD.PARENT_ID = PARENT.ID
AND PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE
ORDER BY ID