-- 코드를 작성해주세요
SELECT A.YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID  
FROM (SELECT *, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA) A 
JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) B
ON A.YEAR = B.YEAR
ORDER BY 1, 2